### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by faroit** [vBaiCai/python-pesq#10]
this package is really useful for the community. Have you considered uploading it to pypi?

**Comment by vBaiCai** [comment]
Good suggestions! I will upload it to PyPI later.

**Comment by shamoons** [comment]
Has this been done?

**Comment by vBaiCai** [comment]
Now, you can find it at https://pypi.org/project/pypesq/1.1/.

**Comment by shamoons** [comment]
```
[pipenv.exceptions.InstallError]: ['Collecting pypesq', '  Downloading https://github.com/vBaiCai/python-pesq/archive/master.zip', 'Requirement already satisfied, skipping upgrade: numpy in /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages (from pypesq->-r /var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pipenv-j3ugwlpe-requirements/pipenv-ml45_du9-requirement.txt (line 1)) (1.17.4)', 'Building wheels for collected packages: pypesq', '  Building wheel for pypesq (setup.py): started', "  Building wheel for pypesq (setup.py): finished with status 'error'", '  Running setup.py clean for pypesq', 'Failed to build pypesq', 'Installing collected packages: pypesq', '  Found existing installation: pypesq 0.0.0', '    Uninstalling pypesq-0.0.0:', '      Successfully uninstalled pypesq-0.0.0', '    Running setup.py install for pypesq: started', "    Running setup.py install for pypesq: finished with status 'error'", '  Rolling back uninstall of pypesq', '  Moving to /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/pypesq-0.0.0.dist-info/', '   from /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/~ypesq-0.0.0.dist-info', '  Moving to /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/pypesq/', '   from /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/~ypesq']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-wheel-2tigg42y --python-tag cp36', '       cwd: /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/', '  Complete output (21 lines):', '  running bdist_wheel', '  running build', '  running build_py', '  file numpy.py (for module numpy) not found', '  creating build', '  creating build/lib.macosx-10.15-x86_64-3.6', '  creating build/lib.macosx-10.15-x86_64-3.6/pypesq', '  copying pypesq/__init__.py -> build/lib.macosx-10.15-x86_64-3.6/pypesq', '  file numpy.py (for module numpy) not found', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building 'pesq_core' extension", '  creating build/temp.macosx-10.15-x86_64-3.6', '  creating build/temp.macosx-10.15-x86_64-3.6/pypesq', '  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Users/shamoon/.pyenv/versions/3.6-dev/include/python3.6m -I/Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/numpy/core/include -c pypesq/pesq.c -o build/temp.macosx-10.15-x86_64-3.6/pypesq/pesq.o', "  pypesq/pesq.c:2:10: fatal error: 'arrayobject.h' file not found", '  #include "arrayobject.h"', '           ^~~~~~~~~~~~~~~', '  1 error generated.', "  error: command 'clang' failed with exit status 1", '  ----------------------------------------', '  ERROR: Failed building wheel for pypesq', '    ERROR: Command errored out with exit status 1:', '     command: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-record-035ke4yr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/include/site/python3.6/pypesq', '         cwd: /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/', '    Complete output (21 lines):', '    running install', '    running build', '    running build_py', '    file numpy.py (for module numpy) not found', '    creating build', '    creating build/lib.macosx-10.15-x86_64-3.6', '    creating build/lib.macosx-10.15-x86_64-3.6/pypesq', '    copying pypesq/__init__.py -> build/lib.macosx-10.15-x86_64-3.6/pypesq', '    file numpy.py (for module numpy) not found', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building 'pesq_core' extension", '    creating build/temp.macosx-10.15-x86_64-3.6', '    creating build/temp.macosx-10.15-x86_64-3.6/pypesq', '    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Users/shamoon/.pyenv/versions/3.6-dev/include/python3.6m -I/Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/numpy/core/include -c pypesq/pesq.c -o build/temp.macosx-10.15-x86_64-3.6/pypesq/pesq.o', "    pypesq/pesq.c:2:10: fatal error: 'arrayobject.h' file not found", '    #include "arrayobject.h"', '             ^~~~~~~~~~~~~~~', '    1 error generated.', "    error: command 'clang' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-record-035ke4yr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/include/site/python3.6/pypesq Check the logs for full command output.']
```

**Comment by vamruta** [comment]
> 
> 
> ```
> [pipenv.exceptions.InstallError]: ['Collecting pypesq', '  Downloading https://github.com/vBaiCai/python-pesq/archive/master.zip', 'Requirement already satisfied, skipping upgrade: numpy in /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages (from pypesq->-r /var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pipenv-j3ugwlpe-requirements/pipenv-ml45_du9-requirement.txt (line 1)) (1.17.4)', 'Building wheels for collected packages: pypesq', '  Building wheel for pypesq (setup.py): started', "  Building wheel for pypesq (setup.py): finished with status 'error'", '  Running setup.py clean for pypesq', 'Failed to build pypesq', 'Installing collected packages: pypesq', '  Found existing installation: pypesq 0.0.0', '    Uninstalling pypesq-0.0.0:', '      Successfully uninstalled pypesq-0.0.0', '    Running setup.py install for pypesq: started', "    Running setup.py install for pypesq: finished with status 'error'", '  Rolling back uninstall of pypesq', '  Moving to /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/pypesq-0.0.0.dist-info/', '   from /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/~ypesq-0.0.0.dist-info', '  Moving to /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/pypesq/', '   from /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/~ypesq']
> [pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-wheel-2tigg42y --python-tag cp36', '       cwd: /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/', '  Complete output (21 lines):', '  running bdist_wheel', '  running build', '  running build_py', '  file numpy.py (for module numpy) not found', '  creating build', '  creating build/lib.macosx-10.15-x86_64-3.6', '  creating build/lib.macosx-10.15-x86_64-3.6/pypesq', '  copying pypesq/__init__.py -> build/lib.macosx-10.15-x86_64-3.6/pypesq', '  file numpy.py (for module numpy) not found', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building 'pesq_core' extension", '  creating build/temp.macosx-10.15-x86_64-3.6', '  creating build/temp.macosx-10.15-x86_64-3.6/pypesq', '  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Users/shamoon/.pyenv/versions/3.6-dev/include/python3.6m -I/Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/numpy/core/include -c pypesq/pesq.c -o build/temp.macosx-10.15-x86_64-3.6/pypesq/pesq.o', "  pypesq/pesq.c:2:10: fatal error: 'arrayobject.h' file not found", '  #include "arrayobject.h"', '           ^~~~~~~~~~~~~~~', '  1 error generated.', "  error: command 'clang' failed with exit status 1", '  ----------------------------------------', '  ERROR: Failed building wheel for pypesq', '    ERROR: Command errored out with exit status 1:', '     command: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-record-035ke4yr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/include/site/python3.6/pypesq', '         cwd: /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/', '    Complete output (21 lines):', '    running install', '    running build', '    running build_py', '    file numpy.py (for module numpy) not found', '    creating build', '    creating build/lib.macosx-10.15-x86_64-3.6', '    creating build/lib.macosx-10.15-x86_64-3.6/pypesq', '    copying pypesq/__init__.py -> build/lib.macosx-10.15-x86_64-3.6/pypesq', '    file numpy.py (for module numpy) not found', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building 'pesq_core' extension", '    creating build/temp.macosx-10.15-x86_64-3.6', '    creating build/temp.macosx-10.15-x86_64-3.6/pypesq', '    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Users/shamoon/.pyenv/versions/3.6-dev/include/python3.6m -I/Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/lib/python3.6/site-packages/numpy/core/include -c pypesq/pesq.c -o build/temp.macosx-10.15-x86_64-3.6/pypesq/pesq.o', "    pypesq/pesq.c:2:10: fatal error: 'arrayobject.h' file not found", '    #include "arrayobject.h"', '             ^~~~~~~~~~~~~~~', '    1 error generated.', "    error: command 'clang' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/bin/python3.6 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-install-w0hplqbm/pypesq/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /private/var/folders/sv/71lvmrjn4yb624vgryr0f4dw0000gn/T/pip-record-035ke4yr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/shamoon/.local/share/virtualenvs/speech-enhancement-asr-Gcsjgcof/include/site/python3.6/pypesq Check the logs for full command output.']
> ```

Did you find solution for this?
