### ISSUE TITLE
processing error

### ISSUE THREAD

**Issue by LucySha** [vBaiCai/python-pesq#11]
both ref and deg have non-zero values, fs = 16000, but pesq(ref, deg, fs) raises "Processing error"

**Comment by LucySha** [comment]
pesq(ref, deg, fs) works right, but pesq(deg, ref, fs) raises "Processing error". In my opinion , pesq compares the score between two audios, and the posilition in the function peaq() couldn't influence the results.

**Comment by vBaiCai** [comment]
Actually, PESQ is sensitive to the position as you say.

In some cases, PESQ cannot be computed. 

You also can try the [C version of PESQ]( https://www.itu.int/rec/T-REC-P.862-200102-I).
