### ISSUE TITLE
PESQ between noisy and enhanced version of speech.

### ISSUE THREAD

**Issue by BilalDendani** [vBaiCai/python-pesq#12]
Hello everyone, 
If I do not have a clean version of speech .
Can I compute the PESQ between the noisy original speech and the enhanced speech?
what does that mean ?
Best Regards.

**Comment by vBaiCai** [comment]
If you don't have a reference signal (clean speech), you cannot calculate the PESQ. Of course, you can calculate the PESQ between noisy and enhanced signals. But, I think it is some type of undefined behavior.

**Comment by BilalDendani** [comment]
Thank you for your answer. 
Consider if we have just the noisy data set. We want apply some techniques of speech enhancement. We know that the PESQ measure of speech quality corresponds to the correlation between reference original clean version and the degraded version. In my case, I do not have clean data set. Can I consider to compute PESQ measure as the value of correlation between original noisy and the enhanced version to deduce if my Speech Enhancement technique does improve the speech quality.
