### ISSUE TITLE
failed to install on windows systerm

### ISSUE THREAD

**Issue by Xuzezheng** [vBaiCai/python-pesq#13]
Hi,I failed to install python-pesq on windows neither python3 nor python2.Does python-pesq not support windows?

**Comment by vBaiCai** [comment]
Hi Xuzezheng, I think you may need to install the Microsoft Visual C++ compiler.

**Comment by Xuzezheng** [comment]
I had already installed Visual C++ Build Tools .

Now I successfully install it inspired by you.Thanks!
