### ISSUE TITLE
PESQ

### ISSUE THREAD

**Issue by ahaanparekh** [vBaiCai/python-pesq#16]
Hi vBaiCai! thanks a lot for sharing this. I have been trying to implement PESQ. I was wondering from the code:

from pypesq import pesq
ref, sr = sf.read(...)
deg, sr = sf.read(...)

what exactly is suppose to be the input to sf.read.

Thank you in advance!

**Comment by vBaiCai** [comment]
hi, ahaanparekh
The input to sf.read is the **path** of the audio file.
