### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by whmrtm** [vBaiCai/python-pesq#2]
Hi, 
I had the following error during installation
![image](https://user-images.githubusercontent.com/8678929/52001002-6af56800-248c-11e9-9960-837b37f13b1f.png)
Is it a problem of my gcc compiler?

**Comment by vBaiCai** [comment]
Hi，whmrtm
I'm not sure what caused this problem, actually. Can you build other python extensions in your environment?
You may refer to the link below:
 * https://askubuntu.com/questions/819072/fatal-error-python-h-no-such-file-or-directory-when-compiling-python-file-to
 * https://www.cyberciti.biz/faq/debian-ubuntu-linux-python-h-file-not-found-error-solution/

**Comment by whmrtm** [comment]
Thanks for the reply, it seems to be my virtual environment problem.
