### ISSUE TITLE
Problem when using setup.py

### ISSUE THREAD

**Issue by benlin1996** [vBaiCai/python-pesq#23]
Thanks for the useful code.

When I try to run command "python setup.py", there is an error. What is the right command for running setup.py?

Another question is about missing pesq_core module when running init.py. Does this problem fixed after I run setup.py correctly?

Thanks for your help

**Comment by vBaiCai** [comment]
Can you provide detailed information about the error?
Or, you can try this:
```
pip install pypesq
```

**Comment by benlin1996** [comment]
Thanks for your help. There is a missing tools in windows. But it work when I run pip3 install . in linux
