### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lcxsnow** [vBaiCai/python-pesq#26]
![image](https://user-images.githubusercontent.com/76511659/126404511-be264ef7-946e-4a87-815a-582bcede7877.png)
![image](https://user-images.githubusercontent.com/76511659/126404529-312bff66-25c8-4252-ad6e-31e1ae0e387f.png)
![image](https://user-images.githubusercontent.com/76511659/126404538-e2ff298b-72b2-43f0-85e1-3342f1e1d258.png)

**Comment by vBaiCai** [comment]
I think the duration of the audio file is too short.

**Comment by vBaiCai** [comment]
I think the duration of the audio file is too short.

**Comment by vBaiCai** [comment]
I think the duration of the audio file is too short.

 It caused that PESQ cannot find the correct alignment between degraded and reference audio.

**Comment by lcxsnow** [comment]
But I have other files which are e same as these data.size. They can be PESQ.

**Comment by vBaiCai** [comment]
Of course that can happen，as the duration may not the only reason. 

But，The NoUtteranceError will be raised only if the alignment failed. 

To note that，this is not a bug. It can be expected that audios cannot be aligned in some situations.

If you want to know more details，you can read the specification of PESQ （ITU P.862）.

**Comment by vBaiCai** [comment]
Of course that can happen，as the duration may not the only reason.

But，The NoUtteranceError will be raised only if the alignment failed.

To note that，this is not a bug. It can be expected that audios cannot be aligned in some situations.

If you want to know more details，you can read the specification of PESQ （ITU P.862）
