### ISSUE TITLE
Why are some processing errors occurring?

### ISSUE THREAD

**Issue by IMLHF** [vBaiCai/python-pesq#3]
s

**Comment by vBaiCai** [comment]
Can you provide more details.

**Comment by IMLHF** [comment]
> Can you provide more details.

i'm testing, audio looks normal

**Comment by IMLHF** [comment]
> Can you provide more details.

audio wave is in [-1,1]?

**Comment by IMLHF** [comment]
my audio is in [-32767,+32767], wave/32767 will fix it
